# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerHubServiceConnection: 'DockerConnection'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - script: docker images
      displayName: 'List Docker Images'
    - task: Docker@2
      displayName: 'Login to DockerHub'
      inputs:
        command: login
        containerRegistry: 'DockerConnection'
        arguments: '-u $(DUsername) -p $(DAccessToken)'
    - task: Docker@2
      displayName: 'Push image to Dockerhub'
      inputs:
        command: push
        containerRegistry: 'DockerConnection'
        repository: 'kibrik47/experiment1'
        tags: |
          $(tag)

