name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        docker-version: '20.10.5'

    - name: Set up Docker
      run: |
        docker build -t my-python-app .
        docker run -t my-python-app
